project_id = "ftaxzdnrnhktzbcsejoy"

[functions.process-pdf-to-checklist]
verify_jwt = false

[functions.process-word-to-checklist]
verify_jwt = false

[functions.send-selection-period-notifications]
verify_jwt = false

[functions.send-work-weekend-notifications]
verify_jwt = false

[functions.send-phone-reset]
verify_jwt = false

[functions.verify-phone-reset]
verify_jwt = false

[functions.complete-phone-reset]
verify_jwt = false