project_id = "ftaxzdnrnhktzbcsejoy"

[functions.send-password-reset]
verify_jwt = false

[functions.process-pdf-to-checklist]
verify_jwt = false

[functions.process-word-to-checklist]
verify_jwt = false

[functions.send-selection-period-notifications]
verify_jwt = false

[functions.send-work-weekend-notifications]
verify_jwt = false

[functions.send-phone-reset]
verify_jwt = false

[functions.verify-phone-reset]
verify_jwt = false

[functions.complete-phone-reset]
verify_jwt = false

[functions.send-bulk-payment-reminders]
verify_jwt = true

[functions.send-guest-split-notification]
verify_jwt = false

[functions.backfill-member-profiles]
verify_jwt = true